version: '3.8'

services:
  tgfilebot:
    build:
      context: .
      dockerfile: Dockerfile
    image: lm317379829/tgfilebot:latest
    container_name: tgfilebot
    restart: unless-stopped
    ports:
      - "9981:8080"
    volumes:
      # 首次启动会自动生成 ./files/config.json 模板，请填写后重启容器。
      - ./files:/root/files
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
